workflows:
  flutter-workflow:
    name: Flutter CI/CD
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: 3.35.6
      xcode: latest
      cocoapods: default
      groups:
        - firebase
      # vars:
        # FLUTTER_VERSION: "3.35.6"

    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
          cd tv_series_modul
          flutter pub get
          cd ..

      - name: Generate mock files
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs

#      - name: Analyze code
#        script: |
#          flutter analyze

      - name: Run tests
        script: |
          flutter test --coverage

      - name: Build APK
        script: |
          flutter build apk --debug

    artifacts:
      - build/app/outputs/**/*.apk
      - coverage/lcov.info

    publishing:
      email:
        recipients:
          - teoprayoga@gmail.com
        notify:
          success: true
          failure: true
